### ISSUE TITLE
What's the function of getCompoundPaddingXXX() functions?

### ISSUE THREAD

**Issue by velis74** [pellucide/Android-Switch-Demo-pre-4.0#13]
In my case (Android 4.x & 5.x), these overrides caused the switch layout rectangle to be twice its desired height. Because physical switch dimensions were added to padding area. That caused pretty awesome layout issues :)
Do these functions play any significant role in Android 2.x? Edit: Just tried in Froyo and it's working normally with these functions commented out.

**Comment by pellucide** [comment]
Its been a while since I looked at this code.I don't really remember why I had these. I will run it with 4.x and 5.x today and see if these functions can be removed.

**Comment by velis74** [comment]
I have determined that these functions (in all 4 variants, not just 2 that are in the code) would be needed in order to support padding attribute.

I have made some modifications with the code. In particular, default look without any specified attributes. I tried to make it look similar to lollipop switch, but still with text displayed. I have so little time right now so I don't know if I'll be able to test your demo app to see how it works with the modifications in order to properly publish the source code. Would you review / include a pull request or is this project a dead one for you?

**Comment by pellucide** [comment]
I will be able to spend some time on it tonight and tomorrow.  Please send the pull request.

**Comment by velis74** [comment]
OK, I sent the pull request. Please note though that I have not attempted to implement the padding attribute.

**Comment by pellucide** [comment]
Thank. I will merge it after doing the review
